import React from "react";
const About = () => (
    <div>
        <h2>About</h2>
        Some details about the web page:
        +...
        +...
        +...
        +...
    </div>
);
export default About;